"use client";

/**
 * AkasGatha Language System — canonical config + re-export barrel.
 *
 * New imports:
 *   useLanguage, LanguageProvider → @/components/providers/LanguageProvider
 *   translations, LANGUAGE_LABELS  → @/config/language (this file)
 */

export { useLanguage, LanguageProvider } from "@/components/providers/LanguageProvider";
export type { LanguageMode } from "@/components/providers/LanguageProvider";

import type { LanguageMode } from "@/components/providers/LanguageProvider";

/* ============================================================
   LANGUAGE LABELS
   ============================================================ */
export const LANGUAGE_LABELS: Record<LanguageMode, string> = {
  en:       "English",
  hi:       "हिंदी",
  hinglish: "Hinglish",
  "hi-en":  "Hi + En",
};

/* ============================================================
   TRANSLATIONS — COMPLETE APP-WIDE COPY
   ============================================================ */
export const translations = {
  en: {
    /* Site / meta */
    siteTagline:       "Sky stories and space science, clearly separated",

    /* Hero */
    heroTagline:       "Wonder starts with narrative. Knowledge needs evidence",
    heroSub:           "Explore Vedic sky narratives and modern astronomy without blending myth and science",
    ctaStart:          "Ask Jigyasa",
    ctaExplore:        "Browse Akas Granth",
    safetyLine:        "Tradition is preserved. Science stays testable. Neither becomes the other",

    /* Navbar */
    navHome:           "Home",
    navGranth:         "Akas Granth",
    navAsk:            "Jigyasa",
    navAbout:          "About",

    /* Home sections */
    homeBridgeEyebrow:   "Two lenses",
    homeBridgeTitle:     "Narrative and evidence, kept distinct",
    homeBridgeDesc:      "Wonder begins with story. Understanding requires observation",
    homeBridgeStory:     "Cultural Narrative",
    homeBridgeScience:   "Astronomical Evidence",
    homeBridgeBoundary:  "Clear Boundary",
    homeBridgeLine1:     "Stories carry cultural meaning and inspire curiosity",
    homeBridgeLine2:     "Science describes what observation and measurement confirm",
    homeBridgeLine3:     "Symbolic interpretation and physical evidence remain separate",

    homeJigyasaEyebrow:  "Jigyasa Engine",
    homeJigyasaTitle:    "Ask a question. See both lenses",
    homeJigyasaDesc:     "Each answer shows tradition and evidence side by side",
    homeJigyasaExample:  "Why do eclipses happen, and how are Rahu-Ketu stories connected culturally?",
    homeJigyasaCta:      "Ask Jigyasa",
    homeJigyasaLens1:    "Katha",
    homeJigyasaLens2:    "Vigyan",
    homeJigyasaLens3:    "Pramaan",
    homeJigyasaLens4:    "Drishya",

    homeGranthEyebrow:   "Akas Granth",
    homeGranthTitle:     "Sky knowledge, organized by topic",
    homeGranthDesc:      "Browse narratives, historical astronomy, and modern science",
    homeGranthCta:       "Browse Archive",

    homeStanceEyebrow:   "Learning Approach",
    homeStanceTitle:     "Respect tradition. Require evidence",
    homeStanceDesc:      "Cultural meaning and empirical facts serve different purposes",
    homeStanceCard1:     "Narrative layer",
    homeStanceCard1Desc: "Vedic and Puranic sky stories are presented as tradition, not science",
    homeStanceCard2:     "Evidence layer",
    homeStanceCard2Desc: "Scientific claims require observation, measurement, and reproducibility",
    homeStanceCard3:     "Safety boundary",
    homeStanceCard3Desc: "No predictions, miracle claims, or mythology-as-proof framing",

    /* Features / Dwars */
    featureEyebrow:    "Eight Modules",
    featureTitle:      "Explore through structured modules",
    featureDesc:       "Each module focuses on one dimension of learning",
    feat0:             "Tradition as story, not proof",
    feat1:             "Open questions without invented answers",
    feat2:             "Evidence-based science",
    feat3:             "Narrative and fact separated",
    feat4:             "Confidence, limits, and sources",
    feat5:             "Visual models for clarity",
    feat6:             "Structured inquiry",
    feat7:             "Connected learning paths",

    /* Granth */
    granthEyebrow:     "Akas Granth",
    granthTitle:       "Sky knowledge organized by topic",
    granthSig:         "Browse narratives and evidence side by side",
    granthIntro:       "Select a topic to see both lenses",
    granthCta:         "Ask Jigyasa",

    /* Topics — title + description */
    topic0Title:       "Planets and Grah",
    topic0Desc:        "Symbolic planet roles beside orbital mechanics",
    topic0Angle:       "See where tradition and astronomy describe the same object differently",
    topic1Title:       "Eclipses and Rahu-Ketu",
    topic1Desc:        "Shadow demon narratives beside lunar node alignment",
    topic1Angle:       "Rahu and Ketu are names for the lunar nodes where eclipses occur",
    topic2Title:       "Nakshatra and Stars",
    topic2Desc:        "27 lunar mansions as cultural sky markers and stellar positions",
    topic2Angle:       "Nakshatras organized the ecliptic for ritual and agricultural timing",
    topic3Title:       "Moon Phases",
    topic3Desc:        "Lunar cycle stories and reflected sunlight geometry",
    topic3Angle:       "Phase changes come from viewing angle, not lunar activity",
    topic4Title:       "Open Questions",
    topic4Desc:        "Unsolved cosmic mysteries without invented answers",
    topic4Angle:       "Learn to ask clear questions where evidence is incomplete",
    topic5Title:       "Time and Calendars",
    topic5Desc:        "Seasonal cycles tracked through celestial observation",
    topic5Angle:       "Vedanga Jyotisha coordinated ritual timing with solstices and lunar cycles",
    topic6Title:       "Space Exploration",
    topic6Desc:        "Historical sky-watching and modern spacecraft missions",
    topic6Angle:       "See how measurement tools advanced from naked eye to instruments",

    /* Ask / Jigyasa */
    askEyebrow:        "Jigyasa Engine",
    askTitle:          "Ask your question",
    askSubtitle:       "See tradition and evidence side by side",
    askSig:            "Structured inquiry for clear learning",
    askPlaceholder:    "Ask about eclipses, moon phases, planets, or star patterns…",
    askLabelQuestion:  "Your Question",
    askLabelTopic:     "Topic",
    askLabelMood:      "Mood",
    askLabelStyle:     "Response Style",
    askButton:         "Submit Question",
    askButtonLoading:  "Analyzing…",
    askMockNote:       "This is a preview response structure. Real AI integration comes in Phase 4B",
    askAwaiting:       "Awaiting Question",
    askSafetyNote:     "Narratives stay symbolic. Science stays evidence-based",

    /* Ask select options */
    topicOptEclipse:   "Eclipses & Rahu-Ketu",
    topicOptPlanets:   "Planets & Grah",
    topicOptStars:     "Nakshatra & Stars",
    moodOptCurious:    "Curious",
    moodOptAnalytical: "Analytical",
    moodOptStory:      "Storyteller",
    styleOptDetailed:  "Detailed Matrix",
    styleOptSummary:   "Quick Summary",

    /* Mock response */
    respKatha:         "Narrative Lens (Katha)",
    respKathaText:     "In Puranic narratives, Rahu and Ketu represent the severed head and body of an asura who gained immortality. Eclipses occur when these entities pursue and temporarily swallow the Sun or Moon, explaining sudden darkness through cosmic drama",
    respVigyan:        "Evidence Lens (Vigyan)",
    respVigyanText:    "Eclipses occur when Earth, Moon, and Sun align. Solar eclipses happen when the Moon passes between Earth and Sun. Lunar eclipses happen when Earth blocks sunlight from reaching the Moon. The orbital crossing points match positions historically called Rahu and Ketu",
    respPramaan:       "Evidence Status (Pramaan)",
    respProven:        "Confirmed",
    respProvenText:    "Orbital mechanics and shadow geometry",
    respSymbolic:      "Symbolic",
    respSymbolicText:  "Demon pursuit narrative",
    respDrishya:       "Visual Model (Drishya)",
    respDrishyaText:   "Eclipse alignment — orbital plane intersection showing lunar nodes",
    respFollowup:      "Follow-up Questions",
    respQ1:            "How often do alignments produce eclipses?",
    respQ2:            "Why not every month?",
    respQ3:            "How did ancient astronomers track the nodes?",

    /* About */
    aboutEyebrow:      "About",
    aboutTitle:        "What is AkasGatha",
    aboutSig:          "Tradition preserved. Evidence required",
    aboutDesc:         "AkasGatha presents Vedic sky narratives and modern astronomy without treating one as proof of the other",
    aboutWhyTitle:     "Purpose",
    aboutWhyDesc:      "Respect cultural sky stories while staying clear about what evidence confirms, what stays symbolic, and what remains unknown",
    aboutSepTitle:     "Separation of concerns",
    aboutSepDesc:      "Narratives carry meaning. Science requires measurement. Keep them separate so evidence remains reliable",
    aboutModTitle:     "Core Modules",
    aboutFutureTitle:  "Development roadmap",
    aboutFutureDesc:   "Phase 4B will integrate real knowledge retrieval and structured AI responses through secure server-side APIs",
    aboutSafetyTitle:  "Safety boundaries",
    aboutSafe1:        "No mythology as scientific proof",
    aboutSafe2:        "No personal predictions or astrology",
    aboutSafe3:        "No deterministic or miracle-based framing",

    /* Footer */
    footerLine:        "AkasGatha — Tradition and evidence, kept distinct",
    footerSafe:        "Narratives stay symbolic. Science stays testable",

    /* Skeleton */
    skeletonLabel:     "Preparing response…",
  },

  hi: {
    siteTagline:       "प्राचीन आकाश कथाएँ, आधुनिक अंतरिक्ष विज्ञान के साथ।",
    heroTagline:       "कथाएँ जिज्ञासा जगाती हैं। विज्ञान स्पष्टता लाता है।",
    heroSub:           "प्राचीन आकाश कथाएँ और आधुनिक अंतरिक्ष विज्ञान को दो स्पष्ट दृष्टिकोणों से समझें।",
    ctaStart:          "जिज्ञासा शुरू करें",
    ctaExplore:        "आकाश ग्रंथ देखें",
    safetyLine:        "सांस्कृतिक कथाएँ कथाएँ रहती हैं। वैज्ञानिक स्पष्टीकरण साक्ष्य-आधारित रहते हैं।",
    navHome:           "होम",
    navGranth:         "आकाश ग्रंथ",
    navAsk:            "जिज्ञासा",
    navAbout:          "परिचय",
    homeBridgeEyebrow:   "दो दृष्टिकोण",
    homeBridgeTitle:     "कथा और विज्ञान, स्पष्ट रूप से अलग।",
    homeBridgeDesc:      "जिज्ञासा कथा से शुरू होती है। स्पष्टता प्रमाण से आती है।",
    homeBridgeStory:     "सांस्कृतिक कथा",
    homeBridgeScience:   "आधुनिक विज्ञान",
    homeBridgeBoundary:  "साक्ष्य की सीमा",
    homeBridgeLine1:     "कथाएँ आश्चर्य और सांस्कृतिक अर्थ बनाती हैं।",
    homeBridgeLine2:     "विज्ञान तंत्र को साक्ष्य से समझाता है।",
    homeBridgeLine3:     "एक दूसरे का प्रमाण नहीं बनता।",
    homeJigyasaEyebrow:  "जिज्ञासा इंजन",
    homeJigyasaTitle:    "आकाश से पूछो। दोनों दृष्टिकोण पढ़ो।",
    homeJigyasaDesc:     "हर प्रश्न एक कथा दृष्टि और एक विज्ञान दृष्टि देता है।",
    homeJigyasaExample:  "ग्रहण क्यों होते हैं, और राहु-केतु की कथाएँ सांस्कृतिक रूप से कैसे जुड़ी हैं?",
    homeJigyasaCta:      "जिज्ञासा आजमाएँ",
    homeJigyasaLens1:    "कथा",
    homeJigyasaLens2:    "विज्ञान",
    homeJigyasaLens3:    "प्रमाण",
    homeJigyasaLens4:    "दृश्य",
    homeGranthEyebrow:   "आकाश ग्रंथ",
    homeGranthTitle:     "हर कक्षा में एक प्रश्न है।",
    homeGranthDesc:      "आकाश कथाओं और साक्ष्य-आधारित विज्ञान के ब्रह्मांडीय संग्रह में झाँकें।",
    homeGranthCta:       "संग्रह देखें",
    homeStanceEyebrow:   "सीखने का नजरिया",
    homeStanceTitle:     "कथाएँ जिज्ञासा जगाती हैं। विज्ञान स्पष्टता लाता है।",
    homeStanceDesc:      "AkasGatha सांस्कृतिक अर्थ और वैज्ञानिक साक्ष्य को स्पष्ट रूप से अलग रखता है।",
    homeStanceCard1:     "कथा परत",
    homeStanceCard1Desc: "सांस्कृतिक कथाएँ आश्चर्य जगाती हैं, तथ्य नहीं।",
    homeStanceCard2:     "विज्ञान परत",
    homeStanceCard2Desc: "वैज्ञानिक स्पष्टीकरण साक्ष्य-आधारित रहते हैं।",
    homeStanceCard3:     "सुरक्षा परत",
    homeStanceCard3Desc: "कोई भविष्यवाणी, चमत्कार, या मिथक-को-प्रमाण भाषा नहीं।",
    featureEyebrow:    "आठ द्वार",
    featureTitle:      "जीवित ब्रह्मांड में प्रवेश करें।",
    featureDesc:       "हर मॉड्यूल ब्रह्मांडीय ज्ञान के एक आयाम का द्वार है।",
    feat0:             "सांस्कृतिक कथाएँ।",
    feat1:             "खुले रहस्य, बिना झूठी निश्चितता के।",
    feat2:             "साक्ष्य से आधुनिक विज्ञान।",
    feat3:             "दो दृष्टिकोण, स्पष्ट रूप से अलग।",
    feat4:             "साक्ष्य, विश्वास और सीमाएँ।",
    feat5:             "जटिल विचारों को गति में देखें।",
    feat6:             "जिज्ञासा और संरचना के साथ पूछें।",
    feat7:             "जुड़े सीखने से याद करें।",
    granthEyebrow:     "आकाश ग्रंथ",
    granthTitle:       "आकाश कथाओं और विज्ञान का ब्रह्मांडीय संग्रह।",
    granthSig:         "हर कक्षा में एक प्रश्न है।",
    granthIntro:       "दोनों दृष्टिकोण जानने के लिए विषय चुनें।",
    granthCta:         "जिज्ञासा में पूछें",
    topic0Title:       "ग्रह और गृह",
    topic0Desc:        "कक्षीय विज्ञान के साथ ग्रहीय कथाएँ।",
    topic0Angle:       "प्रतीकात्मक भूमिकाओं की तुलना खगोल विज्ञान से करें।",
    topic1Title:       "ग्रहण और राहु-केतु",
    topic1Desc:        "संरेखण विज्ञान के साथ ग्रहण कथाएँ।",
    topic1Angle:       "सांस्कृतिक कथा को साक्ष्य-आधारित यांत्रिकी से अलग करें।",
    topic2Title:       "नक्षत्र और तारे",
    topic2Desc:        "तारा पैटर्न, आकाश मार्कर, और सांस्कृतिक नामकरण।",
    topic2Angle:       "आधुनिक तारकीय अवलोकन से पैटर्न पहचान जोड़ें।",
    topic3Title:       "चंद्र चक्र",
    topic3Desc:        "चंद्र कथाएँ और परावर्तित सूर्यप्रकाश की ज्यामिति।",
    topic3Angle:       "ज्यामिति से चंद्रमा के हर चरण को समझें।",
    topic4Title:       "ब्रह्मांडीय रहस्य",
    topic4Desc:        "अंतरिक्ष के खुले प्रश्न — साक्ष्य और कल्पना अलग।",
    topic4Angle:       "जहाँ विज्ञान के पास आंशिक उत्तर हैं, वहाँ ध्यान से पूछें।",
    topic5Title:       "काल चक्र",
    topic5Desc:        "कैलेंडर, ऋतुएँ, और आवर्ती आकाश पैटर्न।",
    topic5Angle:       "देखें कैसे अवलोकन ने समाजों को समय ट्रैक करने में मदद की।",
    topic6Title:       "अंतरिक्ष अभियान",
    topic6Desc:        "प्राचीन जिज्ञासा आधुनिक अंतरिक्ष यान से मिलती है।",
    topic6Angle:       "मिशन विज्ञान से जानें कैसे साक्ष्य एकत्र होता है।",
    askEyebrow:        "जिज्ञासा इंजन",
    askTitle:          "आकाश से पूछो।",
    askSubtitle:       "अपना ब्रह्मांडीय प्रश्न पूछें।",
    askSig:            "आकाश से पूछो। दोनों दृष्टिकोण पढ़ो।",
    askPlaceholder:    "ग्रहण, चंद्र चक्र, ग्रह, या तारा कथा के बारे में पूछें…",
    askLabelQuestion:  "आपका प्रश्न",
    askLabelTopic:     "विषय",
    askLabelMood:      "मनोदशा",
    askLabelStyle:     "उत्तर शैली",
    askButton:         "संरचित उत्तर खोजें",
    askButtonLoading:  "विश्लेषण हो रहा है…",
    askMockNote:       "यह एक संरचित उत्तर पूर्वावलोकन है। वास्तविक AI उत्तर बाद के चरण में आएंगे।",
    askAwaiting:       "आपके प्रश्न की प्रतीक्षा है",
    askSafetyNote:     "सांस्कृतिक कथाएँ कथाएँ रहती हैं। वैज्ञानिक स्पष्टीकरण साक्ष्य-आधारित रहते हैं।",
    topicOptEclipse:   "ग्रहण और राहु-केतु",
    topicOptPlanets:   "ग्रह और गृह",
    topicOptStars:     "नक्षत्र और तारे",
    moodOptCurious:    "जिज्ञासु",
    moodOptAnalytical: "विश्लेषणात्मक",
    moodOptStory:      "कथाकार",
    styleOptDetailed:  "विस्तृत मैट्रिक्स",
    styleOptSummary:   "त्वरित सारांश",
    respKatha:         "कथा दृष्टि",
    respKathaText:     "सांस्कृतिक कथाओं में, राहु और केतु छाया संस्थाओं के रूप में वर्णित हैं जो ब्रह्मांडीय पीछा में लगे हैं। ग्रहण तब होते हैं जब वे सूर्य या चंद्रमा को अस्थायी रूप से निगल लेते हैं।",
    respVigyan:        "विज्ञान दृष्टि",
    respVigyanText:    "वैज्ञानिक रूप से, ग्रहण तब होता है जब पृथ्वी, चंद्रमा और सूर्य अंतरिक्ष में एक रेखा में आते हैं। सूर्य ग्रहण तब होता है जब चंद्रमा पृथ्वी और सूर्य के बीच आता है। चंद्र ग्रहण तब होता है जब पृथ्वी की छाया चंद्रमा पर पड़ती है।",
    respPramaan:       "प्रमाण नोट",
    respProven:        "प्रमाणित",
    respProvenText:    "कक्षीय यांत्रिकी और छाया निर्माण।",
    respSymbolic:      "प्रतीकात्मक",
    respSymbolicText:  "छाया संस्थाओं द्वारा पीछा।",
    respDrishya:       "दृश्य दृश्य",
    respDrishyaText:   "ग्रहण संरेखण मॉडल — कक्षीय विमानों का प्रतिच्छेदन।",
    respFollowup:      "अनुवर्ती प्रश्न (जिज्ञासा अग्नि)",
    respQ1:            "पूर्ण संरेखण कितनी बार होता है?",
    respQ2:            "हर महीने ग्रहण क्यों नहीं होता?",
    respQ3:            "प्राचीन खगोलविदों ने नोड्स की गणना कैसे की?",
    aboutEyebrow:      "परिचय",
    aboutTitle:        "AkasGatha क्या है?",
    aboutSig:          "आश्चर्य से यात्रा शुरू होती है। साक्ष्य इसे दिशा देता है।",
    aboutDesc:         "AkasGatha सांस्कृतिक आकाश कथाओं और आधुनिक अंतरिक्ष विज्ञान को दो स्पष्ट दृष्टिकोणों से समझाता है।",
    aboutWhyTitle:     "यह क्यों बना",
    aboutWhyDesc:      "प्राचीन आकाश कथाओं के आश्चर्य का आनंद लेते हुए स्पष्ट रूप से देखें कि विज्ञान क्या माप सकता है।",
    aboutSepTitle:     "कथा और विज्ञान",
    aboutSepDesc:      "कथाएँ जिज्ञासा बनाती हैं। विज्ञान साक्ष्य देता है। हम उन्हें अलग रखते हैं।",
    aboutModTitle:     "मुख्य मॉड्यूल",
    aboutFutureTitle:  "भविष्य की दिशा",
    aboutFutureDesc:   "आगामी चरण सुरक्षित सर्वर-साइड API के माध्यम से संरचित AI उत्तरों को एकीकृत करेंगे।",
    aboutSafetyTitle:  "सुरक्षा नीति",
    aboutSafe1:        "कोई मिथक वैज्ञानिक प्रमाण के रूप में नहीं।",
    aboutSafe2:        "कोई व्यक्तिगत भविष्यवाणी या ज्योतिष दावा नहीं।",
    aboutSafe3:        "कोई नियतात्मक या चमत्कार-प्रमाण भाषा नहीं।",
    footerLine:        "AkasGatha — प्राचीन आश्चर्य। आधुनिक प्रमाण।",
    footerSafe:        "सांस्कृतिक कथाएँ कथाएँ रहती हैं। विज्ञान साक्ष्य-आधारित रहता है।",
    skeletonLabel:     "उत्तर तैयार हो रहा है…",
  },

  hinglish: {
    siteTagline:       "Purani sky stories ko modern space science ke sath samjho",
    heroTagline:       "Kahaniyaan jigyasa jagaati hain. Science clarity laati hai",
    heroSub:           "Purani aakash ki kahaniyaan aur modern space science ko do alag nazariyeon se explore karo",
    ctaStart:          "Jigyasa Start Karo",
    ctaExplore:        "Akas Granth Dekho",
    safetyLine:        "Cultural stories stories rehti hain. Scientific explanations evidence-based rehte hain",
    navHome:           "Home",
    navGranth:         "Akas Granth",
    navAsk:            "Jigyasa",
    navAbout:          "About",
    homeBridgeEyebrow:   "Do Nazariye",
    homeBridgeTitle:     "Kahani aur Vigyan, clearly alag",
    homeBridgeDesc:      "Jigyasa kahani se shuru hoti hai. Clarity evidence se aati hai",
    homeBridgeStory:     "Cultural Kahani",
    homeBridgeScience:   "Modern Science",
    homeBridgeBoundary:  "Evidence ki Seema",
    homeBridgeLine1:     "Kahaniyaan wonder aur cultural meaning deti hain",
    homeBridgeLine2:     "Science mechanism ko evidence se explain karta hai",
    homeBridgeLine3:     "Ek dusre ka proof nahi banta",
    homeJigyasaEyebrow:  "Jigyasa Engine",
    homeJigyasaTitle:    "Aakash se pucho. Dono nazariye padho",
    homeJigyasaDesc:     "Har sawaal ek kahani lens aur ek science lens deta hai",
    homeJigyasaExample:  "Grahan kyun hote hain, aur Rahu-Ketu ki kahaniyaan culturally kaise judi hain?",
    homeJigyasaCta:      "Jigyasa Try Karo",
    homeJigyasaLens1:    "Katha",
    homeJigyasaLens2:    "Vigyan",
    homeJigyasaLens3:    "Pramaan",
    homeJigyasaLens4:    "Drishya",
    homeGranthEyebrow:   "Akas Granth",
    homeGranthTitle:     "Har orbit mein ek sawaal hai",
    homeGranthDesc:      "Sky stories aur evidence-aware science ke cosmic archive mein jhaanko",
    homeGranthCta:       "Archive Explore Karo",
    homeStanceEyebrow:   "Seekhne ka Nazariya",
    homeStanceTitle:     "Kahaniyaan jigyasa jagaati hain. Science clarity laati hai",
    homeStanceDesc:      "AkasGatha cultural meaning aur scientific evidence ko clearly alag rakhta hai",
    homeStanceCard1:     "Kahani Parat",
    homeStanceCard1Desc: "Cultural kahaniyaan wonder deti hain, fact nahi",
    homeStanceCard2:     "Science Parat",
    homeStanceCard2Desc: "Scientific explanations evidence-based rehte hain",
    homeStanceCard3:     "Safety Parat",
    homeStanceCard3Desc: "Koi prediction, miracle, ya myth-as-proof language nahi",
    featureEyebrow:    "Aath Dwar",
    featureTitle:      "Jivit brahmand mein pravesh karo",
    featureDesc:       "Har module cosmic learning ka ek gateway hai",
    feat0:             "Cultural kahaniyaan",
    feat1:             "Khuley rahasya, bina jhoothe yakeen ke",
    feat2:             "Evidence se modern science",
    feat3:             "Do nazariye, clearly alag",
    feat4:             "Evidence, confidence, aur seemaein",
    feat5:             "Complex ideas ko motion mein dekho",
    feat6:             "Curiosity aur structure se pucho",
    feat7:             "Jude seekhne se yaad karo",
    granthEyebrow:     "Akas Granth",
    granthTitle:       "Sky stories aur science ka cosmic archive",
    granthSig:         "Har orbit mein ek sawaal hai",
    granthIntro:       "Dono nazariye jaanne ke liye topic chuniye",
    granthCta:         "Jigyasa Mein Pucho",
    topic0Title:       "Planets aur Grah",
    topic0Desc:        "Orbital science ke saath planetary kahaniyaan",
    topic0Angle:       "Symbolic roles ki tulna astronomy se karo",
    topic1Title:       "Grahan aur Rahu-Ketu",
    topic1Desc:        "Alignment science ke saath grahan kahaniyaan",
    topic1Angle:       "Cultural kahani ko evidence-based mechanics se alag karo",
    topic2Title:       "Nakshatra aur Taare",
    topic2Desc:        "Star patterns, sky markers, aur cultural naming",
    topic2Angle:       "Pattern recognition ko modern stellar observation se jodo",
    topic3Title:       "Chandra Chakra",
    topic3Desc:        "Lunar kahaniyaan aur reflected sunlight ki geometry",
    topic3Angle:       "Geometry se Moon ke har phase ko samjho",
    topic4Title:       "Cosmic Rahasya",
    topic4Desc:        "Space ke khuley sawaal — evidence aur imagination alag",
    topic4Angle:       "Jahaan science ke paas partial jawaab hain, wahan dhyan se pucho",
    topic5Title:       "Kaal Chakra",
    topic5Desc:        "Calendars, seasons, aur repeating sky patterns",
    topic5Angle:       "Dekho kaise observation ne societies ko time track karne mein help ki",
    topic6Title:       "Space Missions",
    topic6Desc:        "Purani curiosity modern spacecraft se milti hai",
    topic6Angle:       "Mission science se samjho kaise evidence gather hota hai",
    askEyebrow:        "Jigyasa Engine",
    askTitle:          "Aakash se pucho",
    askSubtitle:       "Apna cosmic sawaal pucho",
    askSig:            "Aakash se pucho. Dono nazariye padho",
    askPlaceholder:    "Grahan, chandra chakra, planet, ya star kahani ke baare mein pucho…",
    askLabelQuestion:  "Tumhara Sawaal",
    askLabelTopic:     "Topic",
    askLabelMood:      "Mood",
    askLabelStyle:     "Response Style",
    askButton:         "Structured jawab dhundho",
    askButtonLoading:  "Analyze ho raha hai…",
    askMockNote:       "Yeh ek structured response preview hai. Real AI responses baad ke phase mein aayenge",
    askAwaiting:       "Tumhare sawaal ka intezaar hai",
    askSafetyNote:     "Cultural stories stories rehti hain. Scientific explanations evidence-based rehte hain",
    topicOptEclipse:   "Grahan & Rahu-Ketu",
    topicOptPlanets:   "Planets & Grah",
    topicOptStars:     "Nakshatra & Taare",
    moodOptCurious:    "Jigyasu",
    moodOptAnalytical: "Analytical",
    moodOptStory:      "Kahanikar",
    styleOptDetailed:  "Detailed Matrix",
    styleOptSummary:   "Quick Summary",
    respKatha:         "Kahani Lens (Katha)",
    respKathaText:     "Cultural kahaniyoon mein, Rahu aur Ketu chhaya sansthaon ke roop mein darshaye gaye hain. Grahan tab hote hain jab woh Surya ya Chandra ko temporarily nigal lete hain",
    respVigyan:        "Vigyan Lens",
    respVigyanText:    "Scientifically, grahan tab hota hai jab Prithvi, Chandra, aur Surya space mein ek line mein aate hain. Solar eclipse tab hota hai jab Chandra Prithvi aur Surya ke beech aata hai",
    respPramaan:       "Evidence Note (Pramaan)",
    respProven:        "Proven",
    respProvenText:    "Orbital mechanics aur shadow casting",
    respSymbolic:      "Symbolic",
    respSymbolicText:  "Chhaya sansthaon dwara peecha",
    respDrishya:       "Visual Scene (Drishya)",
    respDrishyaText:   "Eclipse Alignment Model — orbital planes ka intersection",
    respFollowup:      "Follow-up Sawaal (Jigyasa Agni)",
    respQ1:            "Perfect alignment kitni baar hoti hai?",
    respQ2:            "Har mahine grahan kyun nahi hota?",
    respQ3:            "Purane astronomers ne nodes calculate kaise kiye?",
    aboutEyebrow:      "Parichay",
    aboutTitle:        "AkasGatha kya hai?",
    aboutSig:          "Wonder se safar shuru hota hai. Evidence ise disha deta hai",
    aboutDesc:         "AkasGatha cultural sky kahaniyaan aur modern space science ko do clearly alag nazariyeon se explain karta hai",
    aboutWhyTitle:     "Yeh kyun bana",
    aboutWhyDesc:      "Purani sky stories ka wonder enjoy karte hue clearly dekhna ki science kya maap sakta hai",
    aboutSepTitle:     "Kahani aur Science",
    aboutSepDesc:      "Kahaniyaan curiosity banati hain. Science evidence deta hai. Hum inhe alag rakhte hain",
    aboutModTitle:     "Core Modules",
    aboutFutureTitle:  "Future Direction",
    aboutFutureDesc:   "Aane waale phases secure server-side APIs ke through structured AI responses integrate karenge",
    aboutSafetyTitle:  "Safety Stance",
    aboutSafe1:        "Koi myth scientific proof ke roop mein nahi",
    aboutSafe2:        "Koi personal prediction ya astrology claim nahi",
    aboutSafe3:        "Koi deterministic ya miracle-proof language nahi",
    footerLine:        "AkasGatha — Purana wonder. Modern evidence",
    footerSafe:        "Cultural stories stories rehti hain. Science evidence-based rehti hai",
    skeletonLabel:     "Jawab tayaar ho raha hai…",
  },

  "hi-en": {
    siteTagline:       "प्राचीन आकाश कथाएँ — Ancient sky stories with modern space science",
    heroTagline:       "कथाएँ जिज्ञासा जगाती हैं।",
    heroSub:           "Stories spark curiosity. Science brings clarity",
    ctaStart:          "Start Jigyasa",
    ctaExplore:        "Explore Akas Granth",
    safetyLine:        "Cultural narratives stay narratives. Science stays evidence-aware",
    navHome:           "Home",
    navGranth:         "Akas Granth",
    navAsk:            "Jigyasa",
    navAbout:          "About",
    homeBridgeEyebrow:   "दो दृष्टिकोण",
    homeBridgeTitle:     "कथा और विज्ञान — Story and Science",
    homeBridgeDesc:      "Curiosity begins with a story. Clarity comes through evidence",
    homeBridgeStory:     "सांस्कृतिक कथा",
    homeBridgeScience:   "Modern Science",
    homeBridgeBoundary:  "Evidence Boundary",
    homeBridgeLine1:     "Stories build wonder and cultural meaning",
    homeBridgeLine2:     "Science explains mechanisms using evidence",
    homeBridgeLine3:     "One does not become proof of the other",
    homeJigyasaEyebrow:  "Jigyasa Engine",
    homeJigyasaTitle:    "आकाश से पूछो। Read both lenses",
    homeJigyasaDesc:     "Every question returns a story lens and a science lens",
    homeJigyasaExample:  "Why do eclipses happen, and how are Rahu-Ketu stories connected culturally?",
    homeJigyasaCta:      "Try Jigyasa",
    homeJigyasaLens1:    "Katha",
    homeJigyasaLens2:    "Vigyan",
    homeJigyasaLens3:    "Pramaan",
    homeJigyasaLens4:    "Drishya",
    homeGranthEyebrow:   "Akas Granth",
    homeGranthTitle:     "हर कक्षा में एक प्रश्न है।",
    homeGranthDesc:      "Browse the cosmic archive of sky stories and science",
    homeGranthCta:       "Explore the Archive",
    homeStanceEyebrow:   "सीखने का नजरिया",
    homeStanceTitle:     "Stories spark curiosity. Science brings clarity",
    homeStanceDesc:      "AkasGatha keeps cultural meaning and scientific evidence clearly separate",
    homeStanceCard1:     "कथा परत",
    homeStanceCard1Desc: "Cultural narratives inspire wonder, not proof",
    homeStanceCard2:     "विज्ञान परत",
    homeStanceCard2Desc: "Scientific explanations stay evidence-aware",
    homeStanceCard3:     "Safety layer",
    homeStanceCard3Desc: "No predictions, miracle claims, or mythology-as-proof language",
    featureEyebrow:    "आठ Dwars",
    featureTitle:      "Enter the living universe",
    featureDesc:       "Each module is a gateway into cosmic learning",
    feat0:             "Stories as cultural narratives",
    feat1:             "Open mysteries — without false certainty",
    feat2:             "Modern science through evidence",
    feat3:             "Two lenses, clearly separated",
    feat4:             "Evidence, confidence, and limits",
    feat5:             "See complex ideas in motion",
    feat6:             "Ask with curiosity and structure",
    feat7:             "Remember through connected learning",
    granthEyebrow:     "Akas Granth",
    granthTitle:       "आकाश कथाओं का संग्रह — A cosmic archive",
    granthSig:         "हर कक्षा में एक प्रश्न है।",
    granthIntro:       "Choose a topic to explore both lenses",
    granthCta:         "Ask in Jigyasa",
    topic0Title:       "Planets और Grah",
    topic0Desc:        "Planetary stories alongside orbital science",
    topic0Angle:       "Compare symbolic roles with astronomy",
    topic1Title:       "Eclipses और Rahu-Ketu",
    topic1Desc:        "Eclipse narratives beside the science of alignment",
    topic1Angle:       "Separate cultural narrative from mechanics",
    topic2Title:       "Nakshatra और Stars",
    topic2Desc:        "Star patterns and cultural naming traditions",
    topic2Angle:       "Connect pattern recognition with stellar science",
    topic3Title:       "Moon Phases — चंद्र चक्र",
    topic3Desc:        "Lunar stories and the geometry of phases",
    topic3Angle:       "Learn how geometry explains each phase",
    topic4Title:       "Cosmic Mysteries — ब्रह्मांडीय रहस्य",
    topic4Desc:        "Open questions — evidence and imagination distinct",
    topic4Angle:       "Practice careful questioning",
    topic5Title:       "Time Cycles — काल चक्र",
    topic5Desc:        "Calendars, seasons, sky patterns",
    topic5Angle:       "See how observation tracked time",
    topic6Title:       "Space Missions",
    topic6Desc:        "Ancient curiosity meets modern spacecraft",
    topic6Angle:       "Use mission science to understand evidence gathering",
    askEyebrow:        "Jigyasa Engine",
    askTitle:          "आकाश से पूछो।",
    askSubtitle:       "Ask your cosmic question",
    askSig:            "Ask the sky. Read both lenses",
    askPlaceholder:    "Ask about an eclipse, moon phase, planet, or star story…",
    askLabelQuestion:  "Your Question",
    askLabelTopic:     "Topic",
    askLabelMood:      "Mood",
    askLabelStyle:     "Response Style",
    askButton:         "Seek structured answer",
    askButtonLoading:  "Analyzing…",
    askMockNote:       "This is a structured response preview. Real AI responses come in a later phase",
    askAwaiting:       "Awaiting your query",
    askSafetyNote:     "Cultural narratives stay narratives. Science stays evidence-aware",
    topicOptEclipse:   "Eclipses & Rahu-Ketu",
    topicOptPlanets:   "Planets & Grah",
    topicOptStars:     "Nakshatra & Stars",
    moodOptCurious:    "Curious",
    moodOptAnalytical: "Analytical",
    moodOptStory:      "Storyteller",
    styleOptDetailed:  "Detailed Matrix",
    styleOptSummary:   "Quick Summary",
    respKatha:         "Story Lens (Katha)",
    respKathaText:     "In cultural narratives, Rahu and Ketu are described as shadow entities. Eclipses occur when they temporarily swallow the Sun or Moon",
    respVigyan:        "Science Lens (Vigyan)",
    respVigyanText:    "Scientifically, an eclipse occurs when Earth, Moon, and Sun align in space. The orbital nodes match positions ancient astronomers attributed to Rahu and Ketu",
    respPramaan:       "Evidence Note (Pramaan)",
    respProven:        "Proven",
    respProvenText:    "Orbital mechanics and shadow casting",
    respSymbolic:      "Symbolic",
    respSymbolicText:  "The pursuit by shadow entities",
    respDrishya:       "Visual Scene (Drishya)",
    respDrishyaText:   "Eclipse Alignment Model — orbital planes intersection",
    respFollowup:      "Follow-up Questions (Jigyasa Agni)",
    respQ1:            "How often do perfect alignments happen?",
    respQ2:            "Why don't we have an eclipse every month?",
    respQ3:            "How did ancient astronomers calculate the nodes?",
    aboutEyebrow:      "About",
    aboutTitle:        "AkasGatha क्या है?",
    aboutSig:          "Wonder begins the journey. Evidence guides it",
    aboutDesc:         "AkasGatha explains cultural sky narratives and modern space science through two clearly separated lenses",
    aboutWhyTitle:     "यह क्यों बना",
    aboutWhyDesc:      "To help learners explore ancient sky stories while clearly seeing what science can measure",
    aboutSepTitle:     "कथा और Science",
    aboutSepDesc:      "Stories build curiosity. Science provides evidence. We keep them separate",
    aboutModTitle:     "Core Modules",
    aboutFutureTitle:  "Future Direction",
    aboutFutureDesc:   "Upcoming phases will integrate structured AI responses via secure cloud APIs",
    aboutSafetyTitle:  "Safety Stance",
    aboutSafe1:        "No mythology presented as scientific proof",
    aboutSafe2:        "No personal prediction or astrology claims",
    aboutSafe3:        "No deterministic or miracle-proof language",
    footerLine:        "AkasGatha — Ancient wonder. Modern evidence",
    footerSafe:        "Cultural narratives stay narratives. Science stays evidence-aware",
    skeletonLabel:     "Preparing your response…",
  },
} satisfies Record<LanguageMode, Record<string, string>>;

export type TranslationKey = keyof typeof translations["en"];

